## Custom Dockerfile
FROM consol/sakuli-centos-xfce

MAINTAINER c-kr
ENV REFRESHED_AT 2018-02-13
ENV TZ=Europe/Berlin

## Install RDP
USER 0
RUN yum –y install remmina remmina-plugin-rdp
RUN yum clean all

## switch back to default user
USER 1984
